packages:
  - .

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
